# Dictionary of keys in data model. Some keys have the same valid values (e.g. 'Person Grant Number' and 'File Grant Number')
DM_KEY = {
    'Tool Operation': 'Tool Operation',
    'Tool Input Data': 'Tool Input/Output Data',
    'Tool Output Data': 'Tool Input/Output Data',
    'Tool Input Format': 'Tool Input/Output Format',
    'Tool Output Format': 'Tool Input/Output Format',
    'Tool Type': 'Tool Type',
    'Tool Topic': 'Tool Topic',
    'Tool Operating System': 'Tool Operating System',
    'Tool Language': 'Tool Language',
    'Tool License': 'Tool License',
    'Tool Cost': 'Tool Cost',
    'Tool Accessibility': 'Tool Accessibility',
    'Tool Download Type': 'Tool Download Type',
    'Tool Documentation Type': 'Tool Documentation Type',
    'Tool Link Type': 'Tool Link Type',
    'Publication Journal': 'Publication Journal',
    'Publication Assay': 'Assay',
    'Publication Tumor Type': 'Tumor Type',
    'Publication Tissue': 'Tissue',
    'Dataset Assay': 'Assay',
    'Dataset Species': 'Species',
    'Dataset Tumor Type': 'Tumor Type',
    'Dataset Tissue': 'Tissue',
    'Dataset File Formats': 'File Format',
    'Consortium Funding Agency': 'Consortium Funding Agency',
    'Grant Type': 'Grant Type',
    'Project Type': 'Project Type',
    'Working Group Participation': 'Working Group Participation',
    'Chair Roles': 'Chair Roles',
    'Consent For Portal Display': 'Consent For Portal Display',
    'Portal Display': 'Portal Display',
    'Institution Location State': 'Institution Location State',
    'File Format': 'File Format',
    'Tool Grant Number': 'Grant Number',
    'Tool Consortium Name': 'Consortium Name',
    'Publication Grant Number': 'Grant Number',
    'Publication Consortium Name': 'Consortium Name',
    'Publication Theme Name': 'Theme Name',
    'Dataset Grant Number': 'Grant Number',
    'Dataset Consortium Name': 'Consortium Name',
    'Dataset Theme Name': 'Theme Name',
    'Person Grant Number': 'Grant Number',
    'Person Consortium Name': 'Consortium Name',
    'File Grant Number': 'Grant Number',
    'Grant Theme Name': 'Theme Name',
    'Grant Institution Name': 'Grant Institution Name',
    'Grant Institution Alias': 'Grant Institution Alias',
    'Grant Consortium Name': 'Consortium Name',
    'Project Theme Name': 'Theme Name',
    'Project Consortium Name': 'Consortium Name',
    'Project Grant Number': 'Grant Number'
}

# Dictionary of keys in current CV. Values are the keys in the data model.
CV_KEY = {
    'operation': 'Tool Operation',
    'data': 'Tool Input/Output Data',
    'toolFormat': 'Tool Input/Output Format',
    'toolType': 'Tool Type',
    'topic': 'Tool Topic',
    'operatingSystem': 'Tool Operating System',
    'language': 'Tool Language',
    'license': 'Tool License',
    'cost': 'Tool Cost',
    'accessibility': 'Tool Accessibility',
    'downloadType': 'Tool Download Type',
    'documentationType': 'Tool Documentation Type',
    'linkType': 'Tool Link Type',
    'assay': 'Assay',
    'tumorType': 'Tumor Type',
    'tissue': 'Tissue',
    'fileFormat': 'File Format',
    'species': 'Species'
}
